### ISSUE TITLE
Find-WindowHandle returns 0

### ISSUE THREAD

**Issue by odinian** [MScholtes/PSVirtualDesktop#10]
Hello. When I use a Find-WindowHandle on an explorer window that has a disk selected (under This PC), it returns 0. Change the selection to a folder, and it worlk as expected.  easy to replicate. Open an explorer window, click the > next to This PC, and select the C: drive, run this code. Then select a folder on the left navigation pane in explorer, and run this code.

```
# source the Virtual Desktops modules
. C:\Users\allan\Documents\WindowsPowerShell\Scripts\VirtualDesktop.ps1

# assume there are explorer windows open, and we need to move them to the new Desktop
$explorerObject = New-Object -com "Shell.Application"
$explorerWindowTitles = $explorerObject.windows() | select-object LocationName
foreach ($i in $explorerWindowTitles) {
  $wh = Find-WindowHandle $i.LocationName
  write-host " location:" $i.LocationName " handle: $wh"
}
```

**Comment by MScholtes** [comment]
Hello odinian,

I can see no error, working fine for me. 

Please check if the name of your **explorer** window is the same as the value of **LocationName**.
Maybe you have activated the option **_Display the full path in the title bar_** in the _windows explorer_ options? Then those values are different.

Greetings

Markus

**Comment by odinian** [comment]
I do have view full path on. I also have labels for my drives.

Here are my results of the code above:

 location: Music  handle: 852978
 location: Sabrent 2TB (D:)  handle: 0
 location: Development  handle: 3343412

note that for second list (D:), the handle is 0.

and, no, the title of the Window is just D:\. That said, turning off Show Full Path and the code above works, even with the label. 

 location: Music  handle: 852978
 location: Sabrent 2TB (D:)  handle: 1248602
 location: Development  handle: 3343412

So, how to get Find-WindowHandle to work on a drive only window in explorer when the Show Path option is on?

**Comment by MScholtes** [comment]
Hello odinian,

there seems to be a misunderstanding: as stated in the description **Find-WindowHandle** finds a window based on the title text of the window. That's what the commandlet does and I see no misbehaviour in your description, because the property **LocationName** is NOT the same as the window title (but it can be). You can execute **Find-WindowHandle \*** to verify (this shows handles of all windows).

Why don't you use the property **HWND** instead of **LocationName**, you would get the window handle directly?

Greetings

Markus

**Comment by odinian** [comment]
Excellent! The reason I didn't use HWND is because I was using some sample code from the internet and I'm new to Powershell and I don't know what I'm doing :-). I have lots of AppleScript, bash and python experience, but new to PS (and Windows - 35 years on the Mac). I did write out various object properties to see what was available, but I guess I missed HWND. HWDN works perfectly.

That said, it does appear the Show Full Path changes the reported windows title in Find-WindowHandle *
With it on, Find-WindowHandle * reports
E:\                                                                                    852978
C:\                                                                                   1248602
D:\                                                                                   3343412

with it off:
Sabrent 2TB (D:)                                                                      3343412
backup (E:)                                                                            852978
system (C:)                                                                           1248602

but the LocationName property always shows the volume label. I guess the anomaly is really with how Explorer is report LocationName. At any rate, I very mush appreciate your help.

**Comment by odinian** [comment]
Oh, here's my simple script I run at start up. Why goal is to move all the explorer windows from the first desktop to the second desktop. I use the option in Explorer to "Restore previous folder windows at login", then this script runs (using ps2exe. THis might help someone else, so here it is:

# script to manage Virtual Desktops

# source the Virtual Desktops modules
. D:\Development\WindowsPowerShell\Scripts\VirtualDesktop.ps1

# see if there is an "extra" Desktop
if ($(Get-DesktopCount) -eq 1)
{
  "Create a new Desktop"
  $NewDesktop = New-Desktop
  sleep 1
}
else
{
  $NewDesktop = Get-Desktop 1
}

# assume there are explorer windows open, and we need to move them to the new Desktop
$explorerObject = New-Object -com "Shell.Application"
$explorerWindowTitles = $explorerObject.windows() 
foreach ($i in $explorerWindowTitles) {
  Move-Window $NewDesktop $i.HWND
}
