### ISSUE TITLE
Windows 11: The type initializer for 'VirtualDesktop.DesktopManager' threw an exception

### ISSUE THREAD

**Issue by rcragun** [MScholtes/PSVirtualDesktop#14]
Commands from the module fail for me on Powershell 5.1 on Windows 11 but not on Windows 10.

OS: 

- Windows 11 Home
- Version 21H2
- OS build 22000.120

`$PSVersionTable`:

| Name  | Value |
| ------------------------------     | -------------- |
| PSVersion                                 | 5.1.22000.65 |
| PSEdition                                  | Desktop        |
| PSCompatibleVersions             | {1.0, 2.0, 3.0, 4.0...} |
| BuildVersion                             | 10.0.22000.65 |
| CLRVersion                               | 4.0.30319.42000 |
| WSManStackVersion                | 3.0 |
| PSRemotingProtocolVersion    | 2.3 |
| SerializationVersion                  | 1.1.0.1 |

Output of `Get-CurrentDesktop`:
```
The type initializer for 'VirtualDesktop.DesktopManager' threw an exception.
At C:\Program Files\WindowsPowerShell\Modules\VirtualDesktop\1.3.1\VirtualDesktop.ps1:1091 char:2
+     $Desktop = [VirtualDesktop.Desktop]::Current
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], TypeInitializationException
    + FullyQualifiedErrorId : System.TypeInitializationException

Exception calling "FromDesktop" with "1" argument(s): "Object reference not set to an instance of an object."
At C:\Program Files\WindowsPowerShell\Modules\VirtualDesktop\1.3.1\VirtualDesktop.ps1:1092 char:42
+ ... ktop number $([VirtualDesktop.Desktop]::FromDesktop($Desktop)) ('$([V ...
+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : NullReferenceException

Exception calling "DesktopNameFromDesktop" with "1" argument(s): "Object reference not set to an instance of an
object."
At C:\Program Files\WindowsPowerShell\Modules\VirtualDesktop\1.3.1\VirtualDesktop.ps1:1092 char:95
+ ... sktop)) ('$([VirtualDesktop.Desktop]::DesktopNameFromDesktop($Desktop ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : NullReferenceException
```

**Comment by rcragun** [comment]
Also fails on PowerShell 7 on Windows 11:

| Name                           | Value |
| ----                           | ----- |
| PSVersion                      | 7.1.3 |
| PSEdition                      | Core
| GitCommitId                    | 7.1.3 |
| OS                             | Microsoft Windows 10.0.22000 |
| Platform                       | Win32NT |
| PSCompatibleVersions           | {1.0, 2.0, 3.0, 4.0…} |
| PSRemotingProtocolVersion      | 2.3 |
| SerializationVersion           | 1.1.0.1 |
| WSManStackVersion              | 3.0 |

Output of `Get-CurrentDesktop`:

```
OperationStopped: C:\Program Files\WindowsPowerShell\Modules\VirtualDesktop\1.3.1\VirtualDesktop.ps1:1091
Line |
1091 |      $Desktop = [VirtualDesktop.Desktop]::Current
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The type initializer for 'VirtualDesktop.DesktopManager' threw an exception.

MethodInvocationException: C:\Program Files\WindowsPowerShell\Modules\VirtualDesktop\1.3.1\VirtualDesktop.ps1:1092
Line |
1092 |  … ktop number $([VirtualDesktop.Desktop]::FromDesktop($Desktop)) ('$([V …
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "FromDesktop" with "1" argument(s): "Object reference not set to an instance of an
     | object."

MethodInvocationException: C:\Program Files\WindowsPowerShell\Modules\VirtualDesktop\1.3.1\VirtualDesktop.ps1:1092
Line |
1092 |  … sktop)) ('$([VirtualDesktop.Desktop]::DesktopNameFromDesktop($Desktop …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "DesktopNameFromDesktop" with "1" argument(s): "Object reference not set to an
     | instance of an object."
```

**Comment by marclehmeier** [comment]
Same error on Windows 11 Business:

output of: Get-DesktopCount

Der Typeninitialisierer für "VirtualDesktop.DesktopManager" hat eine Ausnahme verursacht.
In C:\Program Files\WindowsPowerShell\Modules\VirtualDesktop\1.3.1\VirtualDesktop.ps1:808 Zeichen:46
+ ... rbose "Count of virtual desktops: $([VirtualDesktop.Desktop]::Count)"
+                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], TypeInitializationException
    + FullyQualifiedErrorId : System.TypeInitializationException
 
Der Typeninitialisierer für "VirtualDesktop.DesktopManager" hat eine Ausnahme verursacht.
In C:\Program Files\WindowsPowerShell\Modules\VirtualDesktop\1.3.1\VirtualDesktop.ps1:809 Zeichen:9
+     return [VirtualDesktop.Desktop]::Count
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], TypeInitializationException
    + FullyQualifiedErrorId : System.TypeInitializationException

**Comment by derBernhard** [comment]
Same issue here on Windows 11 Pro. Would be nice to have a fix ;) Is there any progress on that?

Thanks. Cheers,
Bernhard

**Comment by MScholtes** [comment]
Hello @derBernhard,

please be patient. The COM API of the Virtualdesktop interface is still changing.  The Dev channel version is not compatible to Beta channel version is not compatible to Windows 10 21H2 version.

I will only work on this when I know that my work is not in vain.

Greetings

Markus

**Comment by derBernhard** [comment]
Hi Markus,
thanks for clarifying. Next week is the Windows 11 final release, do you think the dependencies will be sorted out then?
Cheers, Bernhard

**Comment by MScholtes** [comment]
The Powershell module VirtualDesktop is working with Windows 11 now, issue solved.

**Comment by mccorkle** [comment]
@MScholtes Looks like Microsoft changed the interface again.   No rush on looking into it, as I don't expect you to keep up with insider previews, I just wanted to let you know that a new break is coming down the pike.  

```
PS C:\Users\mccor> Get-DesktopList
The type initializer for 'VirtualDesktop.DesktopManager' threw an exception.
At C:\Program Files\WindowsPowerShell\Modules\VirtualDesktop\1.5.1\VirtualDesktop.ps1:1070 char:16
+         for ($I = 0; $I -lt [VirtualDesktop.Desktop]::Count; $I++)
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], TypeInitializationException
    + FullyQualifiedErrorId : System.TypeInitializationException
```

Edition: Windows 11 Pro Insider Preview
Version: 22H2
Build: 25182.rs_prerelease.220812-1437
Experience: Windows Feature Experience Pack 1000.25182.1000.0

I'm happy to do any install / exploration on this machine if there is more information you need.
