### ISSUE TITLE
Errors while running Powershell on Windows11

### ISSUE THREAD

**Issue by RhodianSK** [MScholtes/PSVirtualDesktop#16]
While running the [Example.PS1](https://github.com/MScholtes/TechNet-Gallery/blob/master/VirtualDesktop/Example.ps1) file under Powershell 7, I received 3 x errors. Running the same Example.PS1 file under Powershell 5 returned a single error.

Please attached screenshots for details.

![image](https://user-images.githubusercontent.com/99561171/153727970-21f8cb44-b144-462a-a347-c7a60724b420.png)

![image](https://user-images.githubusercontent.com/99561171/153728010-11a8c77c-8b92-49df-bb16-064472ef35c8.png)

**Comment by MScholtes** [comment]
Hello @RhodianSK,

up to now there is no support for _Powershell Core_ in **VirtualDesktop.ps1**. The reason for this is that _Microsoft_ is making _.Net Core_ more and more platform independent. To get support for special tasks like calling COM one has to install an SDK package in .Net Core. This is nothing I can expect from a user that only wants to run _Powershell_ scripts.
I'm reprogramming this COM calls right now and hope to have a Powershell Core compatible version of **VirtualDesktop** soon.

The example script expects that _Powershell_ runs in its own window and not in **Windows Terminal**. This is just an example, but I have a look on it too.

Greetings

Markus

**Comment by MScholtes** [comment]
Hello @RhodianSK,

released the new version 1.5.0 of the module that should solve your issues.

Greetings

Markus

**Comment by RhodianSK** [comment]
Thanks, great job!
