### ISSUE TITLE
Problem with switch

### ISSUE THREAD

**Issue by prsorgen** [MScholtes/PSVirtualDesktop#19]
Hi,
i tried with a simple script to switch between two desktops every x seconds. It works only for a few switches and than it will be lagging on one screen and not switch correctly. Any suggestion?

`while($true)
{
Get-Desktop 1 | Switch-Desktop
Start-Sleep 5
Get-Desktop 0 | Switch-Desktop
} `

**Comment by MScholtes** [comment]
Hello @prsorgen,

I could reproduce the issue you described: Windows stops switching when a window wants to be placed in the foreground and the th switch occurs. You see it when its icon flashes. 

You cannot switch to another desktop until you brought the flashing window in the foreground. I do not know what to do against this behaviour, seems to be a Windows function

Greetings

Markus

**Comment by MScholtes** [comment]
Closed because there is no reaction
