### ISSUE TITLE
22H2 - MS breaking compatibility once again

### ISSUE THREAD

**Issue by morten-egan** [MScholtes/PSVirtualDesktop#21]
Hi,

After update to 22H2, the API is unfortunately broken again, and throwing an exception when trying to create a new virtual desktop:

![virtualDesktop_fault](https://user-images.githubusercontent.com/3696244/194207800-f4a38e83-de75-4480-9a46-5fe47c5e4a2e.png)

Hope you have time to take a look at it.

Thanks,
Morten

**Comment by MScholtes** [comment]
Hello @morten-egan,

seems to be an issue with the 32-bit version of _Powershell_ only. I will investigate. Please use 64-bit version of _Powershell_ so long.

Greetings

Markus

**Comment by morten-egan** [comment]
Hi,

Yes you are correct, 64-Bit version is working. Actually thought I was running 64-Bit as the default powershell to be honest :) Anyways all good for now.

Thanks
Morten
