### ISSUE TITLE
[Bug Report] The type initializer for 'VirtualDesktop.DesktopManager' threw an exception.

### ISSUE THREAD

**Issue by bigplayer-ai** [MScholtes/PSVirtualDesktop#27]
Title: [Bug Report] The type initializer for 'VirtualDesktop.DesktopManager' threw an exception.

Hello,

I encountered an error when running the SyncVirtualDesktops.ps1 script on my Windows 11 22H2 (OS build 22621.1702) machine.

This is the error message I received:
```
---------------------------
Script Error
---------------------------
Error(s) running PowerShell script 'scripts\SyncVirtualDesktops.ps1':

[31;1mOperationStopped: [0mC:\Users\adam\OneDrive\Documents\PowerShell\Modules\VirtualDesktop\1.5.2\VirtualDesktop.ps1:1085[0m
[31;1m[0m[36;1mLine |[0m
[31;1m[0m[36;1m[36;1m1085 | [0m         for ($I = 0; [36;1m$I -lt [VirtualDesktop.Desktop]::Count[0m; $I++)[0m
[31;1m[0m[36;1m[36;1m[0m[36;1m[0m[36;1m     | [31;1m                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~[0m
[31;1m[0m[36;1m[36;1m[0m[36;1m[0m[36;1m[31;1m[31;1m[36;1m     | [31;1mThe type initializer for 'VirtualDesktop.DesktopManager' threw an exception.[0m

---------------------------
OK   
---------------------------

```

This is the PowerShell script that I was trying to run:
```ps1
param (
    [Parameter(Mandatory=$true)][int]$daySegment2,  # 0 = Day, 1 = Night
    [Parameter(Mandatory=$true)][int]$daySegment4,  # -1 = N/A, 0 = Sunrise, 1 = Day, 2 = Sunset, 3 = Night
    [Parameter(Mandatory=$true)][bool]$nightMode,   # True if night mode is enabled
    [Parameter(Mandatory=$false)][string]$imagePath # Path to current wallpaper image
)

If (-Not ($PSBoundParameters.ContainsKey("imagePath"))) {
    Break
}

$currentWinVer = (Get-CimInstance Win32_OperatingSystem).version
$settingsFile = "$((Get-Item $PSCommandPath).BaseName).dat"
$settingsUpdated = $false
if (-Not (Get-Module -ListAvailable -Name VirtualDesktop)) {
    Install-PackageProvider -Name NuGet -Force -Scope CurrentUser
    Install-Module -Name VirtualDesktop -Force -Scope CurrentUser
    $settingsUpdated = $true
} elseif (-Not (Test-Path -Path $settingsFile -PathType Leaf) -Or ($currentWinVer -Ne (Import-Clixml -Path $settingsFile))) {
    Update-Module -Name VirtualDesktop -Force
    $settingsUpdated = $true
}

Get-DesktopList | ForEach-Object {
    if (-Not (Test-CurrentDesktop -Desktop $_.Number)) {
        Set-DesktopWallpaper -Desktop $_.Number -Path $imagePath
    }
}

if ($settingsUpdated) {
    $currentWinVer | Export-Clixml -Path $settingsFile
}

```

Could you please help me resolve this issue?

Thank you.

**Comment by MScholtes** [comment]
Hello @bigplayer-ai ,

I'm a bit confused with the Windows versions right now. Which Powershell edition and version do you use?

Greetings

Markus

**Comment by MScholtes** [comment]
Hello @bigplayer-ai ,

another question. Are you running a 32 bit Powershell? PSViertualDesktop only works in 64 bit environments.

Greetings

Markus

**Comment by DoGauss** [comment]
Hello @MScholtes, I'm also affected by that issue:

```
Get-DesktopList
Der Typeninitialisierer für "VirtualDesktop.DesktopManager" hat eine Ausnahme verursacht.
In C:\Program Files\WindowsPowerShell\Modules\VirtualDesktop\1.5.3\VirtualDesktop.ps1:1122 Zeichen:16
+         for ($I = 0; $I -lt [VirtualDesktop.Desktop]::Count; $I++)
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], TypeInitializationException
    + FullyQualifiedErrorId : System.TypeInitializationException

 $error[0].exception
Der Typeninitialisierer für "VirtualDesktop.DesktopManager" hat eine Ausnahme verursacht.

 $error[0].exception.innerexception
Die angegebene Umwandlung ist ungültig.
```

```
$PSVersionTable

Name                      Value
----                      -----
PSVersion                 5.1.23471.1000
PSEdition                 Desktop

Get-ComputerInfo | fl OSName, OSVersion
OsName    : Microsoft Windows 11 Pro Insider Preview
OsVersion : 10.0.23471

(Get-Module VirtualDesktop).Version.ToString()
1.5.3
```

Any suggestions?

**Comment by MScholtes** [comment]
Hello @DoGauss,

_Microsoft_ did a strange thing with _Windows 11 Insider Dev_: they **lowered** the build number from 25309 to 23403 on March 8, 2023!!! No one should do this,

Now the version detection fails in **PSVirtualDesktop**. I uploaded a corrected version here:
[VirtualDesktop.ps1.txt](https://github.com/MScholtes/PSVirtualDesktop/files/11988724/VirtualDesktop.ps1.txt)

Can you download it, remove the extension txt from the name and start a powershell in the download location? 
Execute
. .\VirtualDesktop.ps1
and you can test the change.

Does it work now?

Greetings

Markus

**Comment by DoGauss** [comment]
Hello @MScholtes ,
I got the same result:

```
cd Downloads; . .\VirtualDesktop.ps1; Get-DesktopList
Der Typeninitialisierer für "VirtualDesktop.DesktopManager" hat eine Ausnahme verursacht.
In C:\Users\dgauss\Downloads\VirtualDesktop.ps1:1122 Zeichen:16
+         for ($I = 0; $I -lt [VirtualDesktop.Desktop]::Count; $I++)
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], TypeInitializationException
    + FullyQualifiedErrorId : System.TypeInitializationException

$error[0].exception
Der Typeninitialisierer für "VirtualDesktop.DesktopManager" hat eine Ausnahme verursacht.

$error[0].exception.innerexception
Die angegebene Umwandlung ist ungültig.
```
Is there anything I can help with in debuggin this issue?

**Comment by MScholtes** [comment]
Hello @DoGauss,

ok, then it seems that Microsoft did change the interface again.
Can you try to execute
```
VirtualDesktopInsider.exe /list
```
and
```
VirtualDesktop11.exe /list
```
from the companion project https://github.com/MScholtes/VirtualDesktop to verify that not a change of the HString implementstion is responsible (even executing virtualdesktopserver2022.exe /list might be informational)?

All three commands should fail.

Greetings

Markus

**Comment by DoGauss** [comment]
@MScholtes 
the results are as you expected: all three failed.

```
 .\VirtualDesktop11.exe /list
Unbehandelte Ausnahme: System.TypeInitializationException: Der Typeninitialisierer für "VirtualDesktop.DesktopManager" hat eine Ausnahme verursacht. ---> System.InvalidCastException: Die angegebene Umwandlung ist ungültig.
   bei VirtualDesktop.IServiceProvider10.QueryService(Guid& service, Guid& riid)
   bei VirtualDesktop.DesktopManager..cctor()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei VirtualDesktop.Desktop.get_Count()
   bei VDeskTool.Program.Main(String[] args)

 .\VirtualDesktopInsider.exe /list
Unbehandelte Ausnahme: System.TypeInitializationException: Der Typeninitialisierer für "VirtualDesktop.DesktopManager" hat eine Ausnahme verursacht. ---> System.InvalidCastException: Die angegebene Umwandlung ist ungültig.
   bei VirtualDesktop.IServiceProvider10.QueryService(Guid& service, Guid& riid)
   bei VirtualDesktop.DesktopManager..cctor()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei VirtualDesktop.Desktop.get_Count()
   bei VDeskTool.Program.Main(String[] args)

 .\virtualdesktopserver2022.exe /list
Unbehandelte Ausnahme: System.TypeInitializationException: Der Typeninitialisierer für "VirtualDesktop.DesktopManager" hat eine Ausnahme verursacht. ---> System.InvalidCastException: Die angegebene Umwandlung ist ungültig.
   bei VirtualDesktop.IServiceProvider10.QueryService(Guid& service, Guid& riid)
   bei VirtualDesktop.DesktopManager..cctor()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei VirtualDesktop.Desktop.get_Count()
   bei VDeskTool.Program.Main(String[] args)
```

**Comment by MScholtes** [comment]
Hello @DoGauss,

thank you very much for your tests. It is clear that _Microsoft_ changed the internal _COM API_ once more in Windows Insider. I can't do anything about it now since I do not have an Insider edition.

Maybe there are or will be hints in other repositories, I can only deal with the topic in a few weeks.

Greetings

Markus

**Comment by DoGauss** [comment]
Hi @MScholtes 
I have Win11 available in DEV and GA channels.
Is there anything I can help with narrowing down the issue?

What I can tell you now is: the interface GUID
`[Guid("536D3495-B208-4CC9-AE26-DE8111275BF8")]`
doesn't exist in the registry in DEV - only in GA.

How would I identify what MS used to replace it with?

Thanks a lot,
Dominik

**Comment by MScholtes** [comment]
Hello @DoGauss,

normally I have always used **OleViewDotNet** (https://github.com/tyranid/oleviewdotnet), but this no longer seems to work under Windows 11, as it always crashes when examining the COM APIs for virtual desktops.
And for the **GetVirtualDesktopAPI_DIA** script (https://github.com/NyaMisty/GetVirtualDesktopAPI_DIA), the author did not specify what the required prerequisites are (I suspect Visual Studio 2005, symbols downloaded to E:\Symbols, probably a certain version of Python and an undisclosed number of libraries in undisclosed versions). For me, the script only runs into several errors.
So I am at a loss at the moment.

Greetings

Markus

**Comment by itzjakm** [comment]
@MScholtes try this one, worked for me:
https://github.com/widavies/GetVirtualDesktopAPI_DIA

**Comment by MScholtes** [comment]
@itzjakm, 
and what are the requirements to run the python script?

Greetings

Markus

**Comment by MScholtes** [comment]
Hello @itzjakm,

I could not start it from a bare test machine after installing Python and loading Python modules that were errors to. I guess Visual Studio is required, or maybe only the C++ runtime? In which version? Does there has to be a directory E:\Symbols  - this is referneced in the script?

Greetings

Markus

**Comment by itzjakm** [comment]
Maybe VS is required, did you point to the msdia80.dll?

**Comment by MScholtes** [comment]
Yes, and to the symbols that might be downloaded or cached.

But I also don't have Windows 11 Insider DEV available.

Greetings

Markus

**Comment by t1m0thyj** [comment]
I was able to run the Python script in Windows 11 Canary Dev and have attached the results: [VirtualDesktopAPI_25905.log](https://github.com/MScholtes/PSVirtualDesktop/files/12206140/VirtualDesktopAPI_25905.log)

It seems that `IVirtualDesktopManagerInternal` has been renamed to `IVirtualDesktopManagerInternal2` and has a different set of methods:
```
IID_IVirtualDesktopManagerInternal2: A3175F2D-239C-4BD2-8AA0-EEBA8B0B138E
IID_IVirtualDesktopManagerInternal: 4970BA3D-FD4E-4647-BEA3-D89076EF4B9C

Dumping vftable: const CVirtualDesktopManager::`vftable'{for `IVirtualDesktopManagerInternal2'}
    Method  0: [thunk]:public: virtual long __cdecl Microsoft::WRL::Details::RuntimeClassImpl<struct Microsoft::WRL::RuntimeClassFlags<3>,1,1,0,struct Microsoft::WRL::ChainInterfaces<struct IVirtualDesktopManagerPrivate,struct IVirtualDesktopManagerInternal,struct IVirtualDesktopManagerInternal2,class Microsoft::WRL::Details::Nil,class Microsoft::WRL::Details::Nil,class Microsoft::WRL::Details::Nil,class Microsoft::WRL::Details::Nil,class Microsoft::WRL::Details::Nil,class Microsoft::WRL::Details::Nil,class Microsoft::WRL::Details::Nil>,struct IVirtualDesktopManagerInternal,struct IVirtualDesktopManagerInternal2,struct ISuspendableVirtualDesktopManager,struct IImmersiveWindowMessageNotification,class Microsoft::WRL::FtmBase>::QueryInterface`adjustor{32}' (struct _GUID const & __ptr64,void * __ptr64 * __ptr64) __ptr64 (?QueryInterface@?$RuntimeClassImpl@U?$RuntimeClassFlags@$02@WRL@Microsoft@@$00$00$0A@U?$ChainInterfaces@UIVirtualDesktopManagerPrivate@@UIVirtualDesktopManagerInternal@@UIVirtualDesktopManagerInternal2@@VNil@Details@WRL@Microsoft@@V4567@V4567@V4567@V4567@V4567@V4567@@23@UIVirtualDesktopManagerInternal@@UIVirtualDesktopManagerInternal2@@UISuspendableVirtualDesktopManager@@UIImmersiveWindowMessageNotification@@VFtmBase@23@@Details@WRL@Microsoft@@WCA@EAAJAEBU_GUID@@PEAPEAX@Z)
    Method  1: [thunk]:public: virtual unsigned long __cdecl Microsoft::WRL::Details::RuntimeClassImpl<struct Microsoft::WRL::RuntimeClassFlags<3>,1,1,0,struct Microsoft::WRL::ChainInterfaces<struct IVirtualDesktopManagerPrivate,struct IVirtualDesktopManagerInternal,struct IVirtualDesktopManagerInternal2,class Microsoft::WRL::Details::Nil,class Microsoft::WRL::Details::Nil,class Microsoft::WRL::Details::Nil,class Microsoft::WRL::Details::Nil,class Microsoft::WRL::Details::Nil,class Microsoft::WRL::Details::Nil,class Microsoft::WRL::Details::Nil>,struct IVirtualDesktopManagerInternal,struct IVirtualDesktopManagerInternal2,struct ISuspendableVirtualDesktopManager,struct IImmersiveWindowMessageNotification,class Microsoft::WRL::FtmBase>::AddRef`adjustor{32}' (void) __ptr64 (?AddRef@?$RuntimeClassImpl@U?$RuntimeClassFlags@$02@WRL@Microsoft@@$00$00$0A@U?$ChainInterfaces@UIVirtualDesktopManagerPrivate@@UIVirtualDesktopManagerInternal@@UIVirtualDesktopManagerInternal2@@VNil@Details@WRL@Microsoft@@V4567@V4567@V4567@V4567@V4567@V4567@@23@UIVirtualDesktopManagerInternal@@UIVirtualDesktopManagerInternal2@@UISuspendableVirtualDesktopManager@@UIImmersiveWindowMessageNotification@@VFtmBase@23@@Details@WRL@Microsoft@@WCA@EAAKXZ)
    Method  2: [thunk]:public: virtual unsigned long __cdecl Microsoft::WRL::Details::RuntimeClassImpl<struct Microsoft::WRL::RuntimeClassFlags<3>,1,1,0,struct Microsoft::WRL::ChainInterfaces<struct IVirtualDesktopManagerPrivate,struct IVirtualDesktopManagerInternal,struct IVirtualDesktopManagerInternal2,class Microsoft::WRL::Details::Nil,class Microsoft::WRL::Details::Nil,class Microsoft::WRL::Details::Nil,class Microsoft::WRL::Details::Nil,class Microsoft::WRL::Details::Nil,class Microsoft::WRL::Details::Nil,class Microsoft::WRL::Details::Nil>,struct IVirtualDesktopManagerInternal,struct IVirtualDesktopManagerInternal2,struct ISuspendableVirtualDesktopManager,struct IImmersiveWindowMessageNotification,class Microsoft::WRL::FtmBase>::Release`adjustor{32}' (void) __ptr64 (?Release@?$RuntimeClassImpl@U?$RuntimeClassFlags@$02@WRL@Microsoft@@$00$00$0A@U?$ChainInterfaces@UIVirtualDesktopManagerPrivate@@UIVirtualDesktopManagerInternal@@UIVirtualDesktopManagerInternal2@@VNil@Details@WRL@Microsoft@@V4567@V4567@V4567@V4567@V4567@V4567@@23@UIVirtualDesktopManagerInternal@@UIVirtualDesktopManagerInternal2@@UISuspendableVirtualDesktopManager@@UIImmersiveWindowMessageNotification@@VFtmBase@23@@Details@WRL@Microsoft@@WCA@EAAKXZ)
    Method  3: [thunk]:public: virtual long __cdecl CVirtualDesktopManager::GetCount`adjustor{24}' (unsigned int * __ptr64) __ptr64 (?GetCount@CVirtualDesktopManager@@WBI@EAAJPEAI@Z)
    Method  4: [thunk]:public: virtual long __cdecl CVirtualDesktopManager::MoveViewToDesktop`adjustor{24}' (struct IApplicationView * __ptr64,struct IVirtualDesktop * __ptr64) __ptr64 (?MoveViewToDesktop@CVirtualDesktopManager@@WBI@EAAJPEAUIApplicationView@@PEAUIVirtualDesktop@@@Z)
    Method  5: [thunk]:public: virtual long __cdecl CVirtualDesktopManager::CanViewMoveDesktops`adjustor{24}' (struct IApplicationView * __ptr64,int * __ptr64) __ptr64 (?CanViewMoveDesktops@CVirtualDesktopManager@@WBI@EAAJPEAUIApplicationView@@PEAH@Z)
    Method  6: [thunk]:public: virtual long __cdecl CVirtualDesktopManager::GetCurrentDesktop`adjustor{24}' (struct IVirtualDesktop * __ptr64 * __ptr64) __ptr64 (?GetCurrentDesktop@CVirtualDesktopManager@@WBI@EAAJPEAPEAUIVirtualDesktop@@@Z)
    Method  7: [thunk]:public: virtual long __cdecl CVirtualDesktopManager::GetDesktops`adjustor{24}' (struct IObjectArray * __ptr64 * __ptr64) __ptr64 (?GetDesktops@CVirtualDesktopManager@@WBI@EAAJPEAPEAUIObjectArray@@@Z)
    Method  8: [thunk]:public: virtual long __cdecl CVirtualDesktopManager::GetAdjacentDesktop`adjustor{24}' (struct IVirtualDesktop * __ptr64,unsigned int,struct IVirtualDesktop * __ptr64 * __ptr64) __ptr64 (?GetAdjacentDesktop@CVirtualDesktopManager@@WBI@EAAJPEAUIVirtualDesktop@@IPEAPEAU2@@Z)
    Method  9: [thunk]:public: virtual long __cdecl CVirtualDesktopManager::SwitchDesktop`adjustor{24}' (struct IVirtualDesktop * __ptr64) __ptr64 (?SwitchDesktop@CVirtualDesktopManager@@WBI@EAAJPEAUIVirtualDesktop@@@Z)
    Method 10: [thunk]:public: virtual long __cdecl CVirtualDesktopManager::SwitchDesktopAndMoveForegroundView`adjustor{24}' (struct IVirtualDesktop * __ptr64) __ptr64 (?SwitchDesktopAndMoveForegroundView@CVirtualDesktopManager@@WBI@EAAJPEAUIVirtualDesktop@@@Z)
    Method 11: [thunk]:public: virtual long __cdecl CVirtualDesktopManager::CreateDesktopW`adjustor{24}' (struct IVirtualDesktop * __ptr64 * __ptr64) __ptr64 (?CreateDesktopW@CVirtualDesktopManager@@WBI@EAAJPEAPEAUIVirtualDesktop@@@Z)
    Method 12: [thunk]:public: virtual long __cdecl CVirtualDesktopManager::MoveDesktop`adjustor{24}' (struct IVirtualDesktop * __ptr64,unsigned int) __ptr64 (?MoveDesktop@CVirtualDesktopManager@@WBI@EAAJPEAUIVirtualDesktop@@I@Z)
    Method 13: [thunk]:public: virtual long __cdecl CVirtualDesktopManager::RemoveDesktop`adjustor{24}' (struct IVirtualDesktop * __ptr64,struct IVirtualDesktop * __ptr64) __ptr64 (?RemoveDesktop@CVirtualDesktopManager@@WBI@EAAJPEAUIVirtualDesktop@@0@Z)
    Method 14: [thunk]:public: virtual long __cdecl CVirtualDesktopManager::FindDesktop`adjustor{24}' (struct _GUID const & __ptr64,struct IVirtualDesktop * __ptr64 * __ptr64) __ptr64 (?FindDesktop@CVirtualDesktopManager@@WBI@EAAJAEBU_GUID@@PEAPEAUIVirtualDesktop@@@Z)
    Method 15: [thunk]:public: virtual long __cdecl CVirtualDesktopManager::GetDesktopSwitchIncludeExcludeViews`adjustor{24}' (struct IVirtualDesktop * __ptr64,struct IObjectArray * __ptr64 * __ptr64,struct IObjectArray * __ptr64 * __ptr64) __ptr64 (?GetDesktopSwitchIncludeExcludeViews@CVirtualDesktopManager@@WBI@EAAJPEAUIVirtualDesktop@@PEAPEAUIObjectArray@@1@Z)
    Method 16: [thunk]:public: virtual long __cdecl CVirtualDesktopManager::SetDesktopName`adjustor{24}' (struct IVirtualDesktop * __ptr64,struct HSTRING__ * __ptr64) __ptr64 (?SetDesktopName@CVirtualDesktopManager@@WBI@EAAJPEAUIVirtualDesktop@@PEAUHSTRING__@@@Z)
    Method 17: [thunk]:public: virtual long __cdecl CVirtualDesktopManager::SetDesktopWallpaper`adjustor{24}' (struct IVirtualDesktop * __ptr64,struct HSTRING__ * __ptr64) __ptr64 (?SetDesktopWallpaper@CVirtualDesktopManager@@WBI@EAAJPEAUIVirtualDesktop@@PEAUHSTRING__@@@Z)
    Method 18: [thunk]:public: virtual long __cdecl CVirtualDesktopManager::UpdateWallpaperPathForAllDesktops`adjustor{24}' (struct HSTRING__ * __ptr64) __ptr64 (?UpdateWallpaperPathForAllDesktops@CVirtualDesktopManager@@WBI@EAAJPEAUHSTRING__@@@Z)
    Method 19: [thunk]:public: virtual long __cdecl CVirtualDesktopManager::CopyDesktopState`adjustor{24}' (struct IApplicationView * __ptr64,struct IApplicationView * __ptr64) __ptr64 (?CopyDesktopState@CVirtualDesktopManager@@WBI@EAAJPEAUIApplicationView@@0@Z)
    Method 20: [thunk]:public: virtual long __cdecl CVirtualDesktopManager::CreateRemoteDesktop`adjustor{24}' (struct HSTRING__ * __ptr64,struct IVirtualDesktop * __ptr64 * __ptr64) __ptr64 (?CreateRemoteDesktop@CVirtualDesktopManager@@WBI@EAAJPEAUHSTRING__@@PEAPEAUIVirtualDesktop@@@Z)
    Method 21: [thunk]:public: virtual long __cdecl CVirtualDesktopManager::SwitchRemoteDesktop`adjustor{24}' (struct IVirtualDesktop * __ptr64) __ptr64 (?SwitchRemoteDesktop@CVirtualDesktopManager@@WBI@EAAJPEAUIVirtualDesktop@@@Z)
    Method 22: [thunk]:public: virtual long __cdecl CVirtualDesktopManager::SwitchDesktopWithAnimation`adjustor{24}' (struct IVirtualDesktop * __ptr64) __ptr64 (?SwitchDesktopWithAnimation@CVirtualDesktopManager@@WBI@EAAJPEAUIVirtualDesktop@@@Z)
    Method 23: [thunk]:public: virtual long __cdecl CVirtualDesktopManager::GetLastActiveDesktop`adjustor{24}' (struct IVirtualDesktop * __ptr64 * __ptr64) __ptr64 (?GetLastActiveDesktop@CVirtualDesktopManager@@WBI@EAAJPEAPEAUIVirtualDesktop@@@Z)
    Method 24: [thunk]:public: virtual long __cdecl CVirtualDesktopManager::WaitForAnimationToComplete`adjustor{24}' (void) __ptr64 (?WaitForAnimationToComplete@CVirtualDesktopManager@@WBI@EAAJXZ)
```

**Comment by t1m0thyj** [comment]
@MScholtes Thanks, I have already created a version of the script that works on Win 11 Insider Canary: https://github.com/MScholtes/PSVirtualDesktop/compare/master...t1m0thyj:PSVirtualDesktop:fix/insiders-23471
I've not tested all commands but at least `Set-DesktopWallpaper` works in build 25915.

The main difference I found in `IVirtualDesktopManagerInternal2` (besides a few methods added/removed) was that the `IntPtr hwndOrMon` parameter has been removed from all methods.

One problem I don't know how to solve is which version ranges of Windows have the new API? Microsoft's new version strategy is confusing and doesn't help 😆 The definition of the `IsVirtualDesktopV2` variable is based on my best guess:
* 22631.2048 and newer release numbers - First Beta version I saw the problem reported in by @7HE-W0R1D [here](https://github.com/t1m0thyj/WinDynamicDesktop/issues/532)
* 23471 and newer Dev builds - First Dev version I saw the problem reported in by @DoGauss 
* 25381 and newer Canary builds - This version came out around the same time as 23471. It should really be an older version since I'd expect changes take some time to propagate from Canary to Dev, but it probably doesn't matter much because I doubt many users stay on old Canary builds.
* Does _not_ include 22621.1702 which is the version originally mentioned by @bigplayer-ai. The current version of PSVirtualDesktop (1.5.3) works without any issues for me in the latest stable Win 11 build which is newer (22621.1992).

**Comment by MScholtes** [comment]
Hello @t1m0thyj,

thank you very much, that's great. I will have a look at it the end of the week.

Greetings

Markus

**Comment by MScholtes** [comment]
OK, I have made two attempts:

The first attempt (attached **VirtualDesktopV1.ps1**) assumes that the API is the same from Windows 11 build 22631 (the intended version 23H2) upwards.

The second attempt (attached **VirtualDesktopV2.ps1**) assumes that the API from Build 22631 onwards is the same as the API from Windows Insider Beta before 8 March 2023 and that a new API applies from Insider Dev onwards.

I'm curious to see if this works (not very likely due to the "flying blind" I do). Please remove the additional extension _txt_ from the files and try the following in the directory of the scripts:

```powershell
. .\VirtualDesktopV1.ps1
Get-DesktopList
```
und
```powershell
. .\VirtualDesktopV2.ps1
Get-DesktopList
```

I am also not happy with the use of _IVirtualDesktopManagerInternal2_.

Greetings

Markus
[VirtualDesktopV2.ps1.txt](https://github.com/MScholtes/PSVirtualDesktop/files/12267778/VirtualDesktopV2.ps1.txt)
[VirtualDesktopV1.ps1.txt](https://github.com/MScholtes/PSVirtualDesktop/files/12267780/VirtualDesktopV1.ps1.txt)

**Comment by DoGauss** [comment]
Hi @MScholtes,

Both variants worked during a quick test drive.
I couldn't find a functional difference at first glance.
I'll test more next week an will come back to you.

**Comment by MScholtes** [comment]
Hello @DoGauss,

this is great news. I hope out there is someone to test on

- Windows 11 23H2 Beta Insider (only with build 22631, with build 22621 there seems to be a kind of failure on-off situation with every build)
- Windows 11 Insider Canary

Greetings

Markus

**Comment by t1m0thyj** [comment]
@MScholtes I ran the following command on Win11 Insider Canary build 25915:
```ps1
Get-DesktopList | ForEach-Object {
    Set-DesktopWallpaper -Desktop $_.Number -Path "$PSScriptRoot\wallpaper.jpg"
}
```

The V1 script worked without any errors.
The V2 script displayed an error, but still appeared to work:
```
Add-Type : Cannot add type. The type name 'VirtualDesktop.HString' already exists.
At C:\Users\tandr\Downloads\PSVirtualDesktop\VirtualDesktopV2.ps1:29 char:1
+ Add-Type -Language CSharp -TypeDefinition @"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (VirtualDesktop.HString:String) [Add-Type], Exception
    + FullyQualifiedErrorId : TYPE_ALREADY_EXISTS,Microsoft.PowerShell.Commands.AddTypeCommand
```

**Comment by MScholtes** [comment]
Hello @t1m0thyj,

thank you again for your valuable help.

The declaration of the type **HString** is only a helping construct because **HString** is not declared in **.Net Core** anymore. Maybe I should check the existence of the type to prevent a multiple declaration attempt.

I hope someone with a Release Preview Insider version can check the scripts too, I am very curious if Microsoft based this version on the old dev or the old beta version (before 8 march).

Greetings

Markus

**Comment by InfinitGit** [comment]
Is what I'm running into below part of the same problem?
![image](https://github.com/MScholtes/PSVirtualDesktop/assets/124841095/7dc88fc0-a5dd-422e-92a5-046100cbcfa2)

Started after an update to Windows ↓

Edition	Windows 11 Home
Version	22H2
Installed on	‎6/‎9/‎2023
OS build	22621.2215
Experience	Windows Feature Experience Pack 1000.22662.1000.0

Happy to provide any info (though I am less code-savvy).

**Comment by t1m0thyj** [comment]
@InfinitGit This is likely the same problem. Could you test the updated scripts following the instructions here? https://github.com/MScholtes/PSVirtualDesktop/issues/27#issuecomment-1666561746

**Comment by MScholtes** [comment]
I have published the new version 1.5.4 of VirtualDesktop in the Powershell Gallery. However, I am not sure whether all versions and commandlets work.

I ask for feedback.

Greetings

Markus

**Comment by 7HE-W0R1D** [comment]
> @InfinitGit This is likely the same problem, since WinDynamicDesktop uses PSVirtualDeskop for the SyncVirtualDesktops script. Could you test the updated scripts following the instructions here? [#27 (comment)](https://github.com/MScholtes/PSVirtualDesktop/issues/27#issuecomment-1666561746)

My Windows version currently is:
Edition	Windows 11 Pro
Version	23H2
Installed on	‎7/‎16/‎2023
OS build	22631.2262
Experience	Windows Feature Experience Pack 1000.22674.1000.0

I tested the above script and V1 works without problem, but V2 (in a new terminal) give the following error
`Line |
1172 |          for ($I = 0; $I -lt [VirtualDesktop.Desktop]::Count; $I++)
     |                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The type initializer for 'VirtualDesktop.DesktopManager' threw an exception.`
     
I have also updated the WDD Sync virtual desktop script but still receive the same error as before.

**Comment by MScholtes** [comment]
Hello,

I released a new bug fix version 1.5.5 today - tested only against Windows 11 22H2.2215. 
According to Microsoft's will, this may become obsolete again with the September update.

It corrects issues with creating, removing and naming desktops on Windows 11 22H2.2215 (reason for the error: _SwitchDesktopAndMoveForegroundView_ is missing in 2215).

I do not know, if this works on Insider versions build 22631 and up. It would be helpful if you try
```powershell
New-Desktop
```
if you own an Insider version and post the result and the build number here.


Greetings

Markus

**Comment by ha-ku** [comment]
I had this problem with WinDynamicDesktop, and after updating to 1.5.5 the problem seems to be solved. New-Desktop and Get-DesktopList both work fine for me now. I'm using Windows 11 22H2 22621.2215.

**Comment by hisbvdis** [comment]
@MScholtes , hello. A new Windows 11 22621.2283 version has been released.
Are you going to support it?

**Comment by MScholtes** [comment]
Hello @hisbvdis,

Windows Patchday is every second Tuesday, so was yesterday.

Microsoft did not tell me the changes so I have to test.

Greetings

Markus

**Comment by MScholtes** [comment]
Seems to be fine with the current version of **PSVirtualDesktop**.

Greetings

Markus

**Comment by MScholtes** [comment]
No further activities required
