### ISSUE TITLE
Windows 11 23H2:  The type initializer for 'VirtualDesktop.DesktopManager' threw an exception 

### ISSUE THREAD

**Issue by VIJAYARAJSVR** [MScholtes/PSVirtualDesktop#28]
I have Windows 11 23H2 OS ,  I am always getting the below error (screenshot attached).

Note: I am running throw command line, I tried with all the .exe file.

![virtual issue](https://github.com/MScholtes/PSVirtualDesktop/assets/121444788/d23206f8-e901-4afa-b07f-698575cd18b8)

**Comment by MScholtes** [comment]
Hello @VIJAYARAJSVR,

Windows 11 23 H2 is not released yet. I guess this is a duplicate to https://github.com/MScholtes/PSVirtualDesktop/issues/27.

Greetings

Markus

**Comment by MScholtes** [comment]
Hello @VIJAYARAJSVR,

do you have build 22631 of Windows 11 (you can see with _WinVer.exe_)?

If yes, it would be great if you would test the two scripts _VirtualDesktopV1.ps1_ and _VirtualDesktopV2.ps1_ from the issue https://github.com/MScholtes/PSVirtualDesktop/issues/27#issuecomment-1666561746 and post the results here.

Greetings

Markus

**Comment by MScholtes** [comment]
I have published the new version 1.5.4 of VirtualDesktop in the Powershell Gallery. However, I am not sure whether all versions and commandlets work.

I ask for feedback.

Greetings

Markus

**Comment by MScholtes** [comment]
Hello,

I released a new bug fix version 1.5.5 today - tested only against Windows 11 22H2.2215. 
According to Microsoft's will, this may become obsolete again with the September update.

It corrects issues with creating, removing and naming desktops on Windows 11 22H2.2215 (reason for the error: _SwitchDesktopAndMoveForegroundView_ is missing in 2215).

I do not know, if this works on Insider versions build 22631 and up. It would be helpful if you try
```powershell
New-Desktop
```
if you own an Insider version and post the result and the build number here.


Greetings

Markus

**Comment by MScholtes** [comment]
No further activities required
