### ISSUE TITLE
new-desktop causes exception "attempted to read or write protected memory"

### ISSUE THREAD

**Issue by chrisloup** [MScholtes/PSVirtualDesktop#32]
Hi, I'm getting this issue. I'm not exactly sure why its happening. 

Windows 22h2 (os build 22621.2215)

virtualdesktop version 1.5.4

Unhandled Exception: System. AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
process exited with code 3221225477 (0xc0000005)] 

![IMG_8733](https://github.com/MScholtes/PSVirtualDesktop/assets/20747159/ef74d923-700f-48c0-9b66-775007dcd2e8)

**Comment by chrisloup** [comment]
psversion 22621 revision 1778
osversion microsoft windows nt 10.0.22621.0

<img width="331" alt="image" src="https://github.com/MScholtes/PSVirtualDesktop/assets/20747159/4f14fd2c-ba02-4511-95d7-f87cd0a7c642">
<img width="590" alt="image" src="https://github.com/MScholtes/PSVirtualDesktop/assets/20747159/72416a7e-e1b8-40fe-8a6d-d692f27d1aaa">

**Comment by chrisloup** [comment]
<img width="576" alt="image" src="https://github.com/MScholtes/PSVirtualDesktop/assets/20747159/a2ac98d9-88be-444d-8b78-72e9bf0147d8">
<img width="306" alt="image" src="https://github.com/MScholtes/PSVirtualDesktop/assets/20747159/87fc2a51-28ef-484a-88cb-852db1cc5cf4">
<img width="525" alt="image" src="https://github.com/MScholtes/PSVirtualDesktop/assets/20747159/1e458db2-5fe3-413e-a914-d161431b9d5b">

same issue with a different pc. did a fresh install of win 11 pro + windows update, + ms office only + windows store updates

**Comment by chrisloup** [comment]
<img width="610" alt="image" src="https://github.com/MScholtes/PSVirtualDesktop/assets/20747159/d582ea73-76a4-4a36-8352-be09872f531e">
if i try version 1.5.2 I get similar error to bug #27 and bug #28

**Comment by MScholtes** [comment]
Hello,

I released a new bug fix version 1.5.5 today - tested only against Windows 11 22H2.2215 - that addresses the issue. 
According to Microsoft's will, this may become obsolete again with the September update.

Greetings

Markus

**Comment by MScholtes** [comment]
No further activities required
