### ISSUE TITLE
support DSC

### ISSUE THREAD

**Issue by jtnord** [MScholtes/PSVirtualDesktop#35]
it would be great if this module provided a [DSC](https://learn.microsoft.com/en-us/powershell/dsc/overview?view=dsc-2.0) commands out of the box to enable management of virtual desktops as code.

possible workaround is to use the `PSDscResources/Script` and call the functions.

The things that make sense to me are
1. create desktop with a name  (or perhaps require the ID)
2. set wallpaper for a speciifc desktop
3. set name for a specific desktop (depending on how the desktops are identified - GUID vs naming)

**Comment by MScholtes** [comment]
Hello @jtnord.

as this is a private project and I do not have the time or a professional environment, I am unfortunately unable to provide an enterprise function such as DSC.

I ask for your understanding.

Greetings

Markus

**Comment by jtnord** [comment]
@MScholtes totally understand.  
having such support is something on my TODO list for managing [my machines](https://github.com/jtnord/os-config-as-code/) with [winget](https://learn.microsoft.com/en-us/windows/package-manager/configuration/).  If I got around to it would you accept a PR to add support, or would you prefer I did it in my own repo and just used this library under the hood?

**Comment by MScholtes** [comment]
Hello @jtnord,

thank you for the offer. However, it does not make sense to add DSC functions to my project as I cannot support them. So a PR is not the right way here, please make a fork and/or your own project.

Greetings

Markus
