### ISSUE TITLE
Throwing errors on latest Win 11 Insider builds

### ISSUE THREAD

**Issue by kilasuit** [MScholtes/PSVirtualDesktop#36]
Just tried installing and using this module both in Windows PowerShell and the latest PowerShell Daily build and getting these errors
Exact build of windows is `10.0.26020.1000`

![image](https://github.com/MScholtes/PSVirtualDesktop/assets/6355225/a7decccd-7747-48d7-a132-5ffeb0e36c8f)

**Comment by Lifailon** [comment]
![image](https://github.com/MScholtes/PSVirtualDesktop/assets/116945542/57b9126d-98dc-46ad-98c5-bb286fbc94a2)

PSVersion                      5.1.19041.3930
BuildVersion                  10.0.19041.3930

PS C:\Users\lifailon> Get-DesktopCount
4
PS C:\Users\lifailon> New-Desktop
IsVisible Left                   Right
--------- ----                   -----
    False VirtualDesktop.Desktop

PS C:\Users\lifailon> Get-DesktopCount
5

**Comment by MScholtes** [comment]
Hello,
it seems that Microsoft has changed the API again, at least in the Dev Channel. I don't have a clear picture yet if other Insider channels are also affected, but I'm sorry to say that I'm not able to keep up with the Windows Insider changes.

Greetings

Markus

**Comment by ysdev** [comment]
This change also appeared on KB5034204, the preview update of this month(e.g. 10.0.22631.3085 for Windows 11 23H2).
Could you confirm it? It might also be included in a security patch on next month.

**Comment by MScholtes** [comment]
Hallo,

as much as I can evaluate and others are reporting, Microsoft did change the API for virtual desktops  for Windows 11 with the preview update and for the Windows Insider channels.
@kilasuit: seems you are using insider canary channel. Sorry, I do not know anything about the changes here.

Greetings

Markus

**Comment by MarekGrossman** [comment]
Hello Markus, 
    I also think that the problem appeared after the KB5034204 was installed. I am not in any Windows insider channels.
Do You have any idea how solve the problem? I am using 13 VD and it is very annoying to switche them without your utility.

Thanks

Mareg

**Comment by MScholtes** [comment]
Hello all,

I uploaded a test release for **Windows 11 23H2 3805**. You can try it out the following way:
- download **VirtualDesktop3085.ps1** from the root of this repository
- start **Powershell** in the same directory as the script
- execute
```powershell
. .\VirtualDesktop3085.ps1
```
- test your commands for virtual desktops

I did successfully test with a _Win11 23H2 3085_, but I do not have _Win11 22H2 3085_ oder _Win11 Insider_. I would be very happy if someone could test this.

Greetings

Markus

**Comment by chrisloup** [comment]
just some updates.
these two machines passed
![image](https://github.com/MScholtes/PSVirtualDesktop/assets/20747159/3c7e7f27-f30b-4699-b272-d97c7228316b)
![image](https://github.com/MScholtes/PSVirtualDesktop/assets/20747159/d906f64a-97d8-4722-a082-40a8f341e64b)

this one did not. 
![image](https://github.com/MScholtes/PSVirtualDesktop/assets/20747159/e3884aaf-fd95-4344-a2fc-b86fc960c12b)
![image](https://github.com/MScholtes/PSVirtualDesktop/assets/20747159/96dc125e-adb1-4079-b107-a293b8e01938)

![image](https://github.com/MScholtes/PSVirtualDesktop/assets/20747159/018e5bab-74b4-4d3a-a211-13f68b183798)

**Comment by MarekGrossman** [comment]
@MScholtes it is work well, thanks, but just in one session, how I show install it in whole system? Do You update repository and after this we should install new version?
Again thanks for help and utility.

Mareg

**Comment by ysdev** [comment]
I confirmed `VirtualDesktop3085.ps1` working on Windows 11 23H2 22631.3155, the monthly update which came today.
Thank you for your help.

**Comment by chrisloup** [comment]
@MScholtes 

sry for the delay. was on holiday.

working machine 1 (22h2 22621.3085)
![image](https://github.com/MScholtes/PSVirtualDesktop/assets/20747159/80ab4758-11c3-4fa5-af2b-0c475ef5cd35)

working machine 2  (23h2 22631.3155)
![image](https://github.com/MScholtes/PSVirtualDesktop/assets/20747159/f962fa61-2002-46bd-bb4b-ad62199ce63f)

Non Working Machine (22h2 22621.3155)
![image](https://github.com/MScholtes/PSVirtualDesktop/assets/20747159/c94e95ad-3517-45bd-9385-b6a77a3318cb)

![image](https://github.com/MScholtes/PSVirtualDesktop/assets/20747159/b7bbebe5-a0c0-45a4-8f4f-d1a4392426bc)

**Comment by MScholtes** [comment]
Hello @chrisloup,
thank you for your feedback, but to use the example version manually, you have to dotsource the script:
```powershell
. .\VirtualDesktop3085.ps1
```
(the leading . is important)

Greetings

Markus

**Comment by MScholtes** [comment]
Hello,

I updated this repository today and the package on PowerShell Gallery. With 
```powershell
Update-Module VirtualDesktop
```
or
```powershell
Install-Module VirtualDesktop
```
you can install the new version 1.5.7.

I do still have no feedback to Windows 11 22H2 with the new patch. If someone would report I would be very thankful.

Greetings

Markus

**Comment by chrisloup** [comment]
> Hello @chrisloup, thank you for your feedback, but to use the example version manually, you have to dotsource the script:
> 
> ```powershell
> . .\VirtualDesktop3085.ps1
> ```
> 
> (the leading . is important)
> 
> Greetings
> 
> Markus

thanks. yes. that same pc I updated with 1.5.7 works as well. so all good at my end.

**Comment by MarekGrossman** [comment]
Great! It's works again. Realy big thanks for this util Markus!

**Comment by kilasuit** [comment]
I haven't tested all the cmdlets but some are working & others are throwing errors or crashing the powershell process. 

Seem to be working
```
Switch-Desktop
Pin-Window
Unpin-Window
```

Crashed PowerShell 
```
New-Desktop
```

Didn't update properly 
```
Set-DesktopName
```

**Comment by kilasuit** [comment]
Latest version of the module on the Gallery.
from winver
![image](https://github.com/MScholtes/PSVirtualDesktop/assets/6355225/cd19eb08-6d16-4207-8941-1bf7eb8ac147)
![image](https://github.com/MScholtes/PSVirtualDesktop/assets/6355225/24aa27cc-3673-4bf9-af89-ab6422a40ca2)


Error from New-Desktop in PowerShell 7.5.0-preview.1
![image](https://github.com/MScholtes/PSVirtualDesktop/assets/6355225/28c396a3-be6d-4e91-9326-3629aa9f080e)


Error from New-Desktop in PowerShell 5.1
![image](https://github.com/MScholtes/PSVirtualDesktop/assets/6355225/f7f33aba-6d01-4ef2-ad9b-4618cbf3a6e5)

**Comment by MScholtes** [comment]
Hello @kilasuit,

it is sad to hear that the changes are not working for the _Canary Insider_ channel. Unfortunately, due to the effort involved, I can't provide support here - especially not for _Canary_, which is constantly undergoing major changes that are often not incorporated into the other versions.

I have adapted the description on the readme page

Greetings

Markus

**Comment by igorakkerman** [comment]
@MScholtes Thank you for your great work.

When Microsoft makes breaking changes to the Windows APIs or the OS behavior, do they publish a list of those changes and the steps to adapt your applications? I didn't dig into the internals to understand how your application works and whether there actually are official API's for what it does.

**Comment by MScholtes** [comment]
Hello @igorakkerman,

Microsoft does not publish any documentation on the interfaces for virtual desktops, as it believes that these functions should only be set by the user.

With every new version, build or monthly patch, there is therefore a risk that COM GUIDs will change or function calls to the API will change. This must be determined by debugging the API, and this for each Windows version individually, as the APIs usually differ between the versions (i.e. for Win10 22H2, Win 10 23H2, Win 11 22H2, Win 11 23H2, Win 11 Insider Beta and Preview and Dev and Canary, also Windows Server [fortunately there are significantly fewer versions]).

So only the community can provide the necessary information, fortunately there are very active helpers. However, there is always the danger that Microsoft will make this impossible.

Greetings

Markus

**Comment by igorakkerman** [comment]
Thank you, @MScholtes, for explaining and for your great reverse-engineering work. It is a pity that Microsoft still doesn't open all Windows APIs, but I don't want to open a more extensive discussion here.

**Comment by MScholtes** [comment]
Issue solved but of Canary versions, but no support for this version
