### ISSUE TITLE
The type initializer for 'VirtualDesktop.DesktopManager' threw an exception

### ISSUE THREAD

**Issue by bostergit** [MScholtes/PSVirtualDesktop#37]
Two days ago, my Windows 11 was upgraded to version 23H2. Now I get the following error:

get-desktoplist

Der Typeninitialisierer für "VirtualDesktop.DesktopManager" hat eine Ausnahme verursacht.
In C:\Program Files\WindowsPowerShell\Modules\VirtualDesktop\1.5.6\VirtualDesktop.ps1:1227 Zeichen:16
+         for ($I = 0; $I -lt [VirtualDesktop.Desktop]::Count; $I++)
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], TypeInitializationException
    + FullyQualifiedErrorId : System.TypeInitializationException

My Windows Version:
Edition	Windows 11 Enterprise
Version	23H2
Installiert am	‎26.‎11.‎2023
Betriebssystembuild	22631.3085
Leistung	Windows Feature Experience Pack 1000.22684.1000.0

**Comment by MScholtes** [comment]
Hello @bostergit,

I can commit the change with Windows 11 and the preview update for Win 11 23H2 (raises build from 3007 to 3085). However, I will wait until the next mandatory update before making any adjustments, otherwise it will no longer work with Windows 11 without this update.

Greetings
Markus

**Comment by yanislavgalyov** [comment]
hello @MScholtes,
any chance of a pre-release with the changes?

**Comment by chrisloup** [comment]
@MScholtes just providing some more datapoints .
(new-desktop crashes on exception)

windows 11 22h2 os build 22621.3085
psversion 5.1.22621.2506
windows version 10.0.22621.0

![image](https://github.com/MScholtes/PSVirtualDesktop/assets/20747159/713ab1d2-79eb-40a9-816a-f84492916e19)
![image](https://github.com/MScholtes/PSVirtualDesktop/assets/20747159/f9dbb7e6-7af1-4c94-8ade-ead87bc1d18e)


windows 11 23h2 os build 22631.3085
psversion 5.1.22621.2506
windows version 10.0.22631


![image](https://github.com/MScholtes/PSVirtualDesktop/assets/20747159/83422465-ea8c-4d62-ae77-4842d4018c35)
![image](https://github.com/MScholtes/PSVirtualDesktop/assets/20747159/67d5298d-5b7b-4dd6-a2db-dbce3524f9b5)

**Comment by bedalus** [comment]
Same for me. Just want to say thanks for providing these tools, really handy.

Windows 11 Pro
23H2
22631.3085
Windows Feature Experience Pack 1000.22684.1000.0

**Comment by bostergit** [comment]
Hello,

thanks. This worked for me. :)

**Comment by yanislavgalyov** [comment]
Works for me. Thanks

Windows 11 Pro
23H2
22631.3085
Windows Feature Experience Pack 1000.22684.1000.0

**Comment by WilliansDutra** [comment]
> Hello all,
> 
> I uploaded a test release for **Windows 11 23H2 3805**. You can try it out the following way:
> 
> * download **VirtualDesktop3085.ps1** from the root of this repository
> * start **Powershell** in the same directory as the script
> * execute
> 
> ```powershell
> . .\VirtualDesktop3085.ps1
> ```
> 
> * test your commands for virtual desktops
> 
> I did successfully test with a _Win11 23H2 3085_, but I do not have _Win11 22H2 3085_ oder _Win11 Insider_. I would be very happy if someone could test this.
> 
> Greetings
> 
> Markus

Worked for me too. Thanks.

**Comment by alex-nikitin-dev** [comment]
> Hello all,
> 
> I uploaded a test release for **Windows 11 23H2 3805**. You can try it out the following way:
> 
> * download **VirtualDesktop3085.ps1** from the root of this repository
> * start **Powershell** in the same directory as the script
> * execute
> 
> ```powershell
> . .\VirtualDesktop3085.ps1
> ```
> 
> * test your commands for virtual desktops
> 
> I did successfully test with a _Win11 23H2 3085_, but I do not have _Win11 22H2 3085_ oder _Win11 Insider_. I would be very happy if someone could test this.
> 
> Greetings
> 
> Markus

works well

**Comment by gopsmith** [comment]
Yesterday's monthly Win 11 updates included the interface changes that break DesktopManager. So far I've been unable to roll my system back to where it was working.

**Comment by MScholtes** [comment]
Hello,

I updated this repository today and the package on PowerShell Gallery. With 
```powershell
Update-Module VirtualDesktop
```
or
```powershell
Install-Module VirtualDesktop
```
you can install the new version 1.5.7.

I do still have no feedback to Windows 11 22H2 with the new patch. If someone would report I would be very thankful.

Greetings

Markus

**Comment by michael-akkermans** [comment]
![issue](https://github.com/MScholtes/PSVirtualDesktop/assets/69667339/d04971d4-1f61-49f3-8b07-9d8eb195d0e2)

Installed 1.5.7 but to no luck.

**Comment by MScholtes** [comment]
Hello @michael-akkermans,

please install the current February Windows Patch, this will raise your Windows version to 22621.3155 and version 1.5.7 of PSVirtualDesktop (I hope) will work. I still have no feedback if there are additional issues with Win 11 22H2.

If you want to wait some days with patching (not recommended), use the older version 1.5.6 of PSVirtualDesktop.

Greetings

Markus

**Comment by michael-akkermans** [comment]
Hi @MScholtes,

Indeed it works with the current February Windows Patch. Thanks for the feedback.

**Comment by MScholtes** [comment]
Issue solved
