### ISSUE TITLE
Setting Wallpaper for Individual Displays with Multi-Monitor Setup

### ISSUE THREAD

**Issue by ThioJoe** [MScholtes/PSVirtualDesktop#40]
Not sure if this is possible at the moment, but it would be cool if it was also possible to set the wallpaper for separate displays within each virtual desktop.

**Comment by MScholtes** [comment]
Hello @ThioJoe,

I found no fitting API call. Are you able to do manually what you want (preparing two virtual desktops with two monitors so you have four different backgrounds and you can switch between them)?

Greetings

Markus

**Comment by ThioJoe** [comment]
Ah I see, I've looked as well and it seems like there might not be a native way to do it either through the GUI.

Though I have found a workaround, which is to basically stitch two wallpapers together to create a combined image, then set that as the wallpaper. You have to go into the Personalization settings under Background and change the "fit" mode to something like Tile, Span, etc depending on how you want it to look. Then it seems like it applies that mode to all virtual desktops. So you'd have to make double wallpaper images for all the virtual desktops.

**Comment by MScholtes** [comment]
Hello @ThioJoe,

since my project only makes calls to an existing Windows API, I don't see any way to fulfil the request at the moment.

Greetings

Markus

**Comment by ThioJoe** [comment]
> Hello @ThioJoe,
> 
> since my project only makes calls to an existing Windows API, I don't see any way to fulfil the request at the moment.
> 
> Greetings
> 
> Markus

I agree, wasn't expecting a miracle 👍 Figured I'd just post a workaround in case anyone found this through google or something

**Comment by MScholtes** [comment]
I assume that the issue no longer exists as there is no feedback.
