### ISSUE TITLE
Slideshow wallpapers

### ISSUE THREAD

**Issue by XFox111** [MScholtes/PSVirtualDesktop#41]
Is there a way to use this module to set a slideshow wallpaper for VDs?

I've tried to specify path to a folder instead of a specific picture with following commands:
```pwsh
Set-DesktopWallpaper -Desktop 1 -Path "C:\Users\[redacted]\OneDrive\Pictures\Wallpapers\"
Set-AllDesktopWallpapers -Path "C:\Users\[redacted]\OneDrive\Pictures\Wallpapers\"
```

The first command didn't yield any errors, but upon switching to this desktop, it uses the first picture from the folder and there's a glitch during switching animation when it shows folder's thumbnail as a wallpaper

<details><summary>Screenshot (click to expand)</summary>
<p>

<img width="1440" alt="2024-03-10" src="https://github.com/MScholtes/PSVirtualDesktop/assets/28831743/df31b704-22bc-4b72-b6f9-18c502d4d272">

</p>
</details>

And the second command throws an exception:

```pwsh
MethodInvocationException: C:\Users\eugen\OneDrive\Documents\PowerShell\Modules\VirtualDesktop\1.5.7\VirtualDesktop.ps1:2026
Line |
2026 |              [VirtualDesktop.Desktop]::SetAllWallpaperPaths($Path)
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "SetAllWallpaperPaths" with "1" argument(s): "Value does not fall within the expected range."
```

**Comment by MScholtes** [comment]
Hello @XFox111,

setting a slideshow wallpaper is no "virtual desktop" setting since it applies to the whole desktop. For this reason there is no _virtual desktop API_ function to achieve this.
Please search the internet, there are several examples to change the wallpaper with _Powershell_.

Greetings

Markus

**Comment by XFox111** [comment]
Ah, I see. I figured that if there's an API to change static wallpapers for each VD, then there should be an API to set a slideshow folder for each VD as well
