### ISSUE TITLE
kb5035942 2024-03 cumulative update preview - minor breakage .

### ISSUE THREAD

**Issue by chrisloup** [MScholtes/PSVirtualDesktop#42]
its minor cos i just have to rewrite the script

new-desktop | Set-desktopname -name "abc" | switch-desktop will fail

new-desktop | Set-desktopname -name "abc" | switch-desktop "abc" will pass

Get-Desktop abc| Switch-Desktop "will pass"

![image](https://github.com/MScholtes/PSVirtualDesktop/assets/20747159/bbb458af-af5e-4261-b619-36a12a920c01)
![image](https://github.com/MScholtes/PSVirtualDesktop/assets/20747159/90d44ce0-b099-400a-ad29-06bddcb40797)
![image](https://github.com/MScholtes/PSVirtualDesktop/assets/20747159/4110e589-df8f-4d16-8559-4add45d70d43)

![image](https://github.com/MScholtes/PSVirtualDesktop/assets/20747159/81043cfd-b5f5-4c3c-b873-40248d4f8d11)

**Comment by MScholtes** [comment]
Hello @chrisloup,

to use the virtual desktop object in a pipeline after **Set-DesktopName** you have to apply the additional parameter **-PassThru**, for example
```powershell
New-Desktop | Set-DesktopName -Name "abc" -PassThru | Switch-Desktop
```

Greetings

Markus

**Comment by chrisloup** [comment]
whoops.. i thought something changed cos i never saw that error message before.
all good then

**Comment by MScholtes** [comment]
You're welcome
