### ISSUE TITLE
Windows 11 24H2 Update broke the wallpaper functionality again 😔

### ISSUE THREAD

**Issue by ThioJoe** [MScholtes/PSVirtualDesktop#44]
The Windows 11 24H2 update was released to the Insider 'Release Preview' channel and seems to have broken this module.

Also it causes some strange behavior in renaming the virtual desktops.

For example, if I use this command:
`Set-DesktopWallpaper -Desktop General -Path 'C:\Users\Joe\Desktop\Test.png' -PassThru`

It doesn't change the wallpaper, but strangely _changes the name of the virtual desktop_ to the image path

Here's a short screen recording demonstrating this behavior (on Google Drive because it's a bit too big for GitHub):
https://drive.google.com/file/d/1w5N5zhmJuprU-VgUGR8Qe2EEGeLv6Z-J/view?usp=sharing

Here's notes for the video:
0:03 - Showing the initial name of the first virtual desktop as "General"
0:10 - Entering the command above
0:15 - Command seems to run without error
0:17 - Virtual desktop name has changed to the image path

-----------------

If I run it with -verbose this is the output:
```
PS C:\Windows\System32> Set-DesktopWallpaper -Desktop General -Path 'C:\Users\Joe\Desktop\Test.png' -PassThru -Verbose
VERBOSE: Set name of desktop number 0 ('General') to 'C:\Users\Joe\Desktop\Test.png'

IsVisible Left Right
--------- ---- -----
     True      VirtualDesktop.Desktop
```

### Some additional things I've tried with the same result:
Running without `-PassThru`:
```
PS C:\Windows\System32> Set-DesktopWallpaper -Desktop General -Path 'C:\Users\Joe\Desktop\Test.png' -Verbose
VERBOSE: Set name of desktop number 0 ('General') to 'C:\Users\Joe\Desktop\Test.png'
```

Running by specifying the desktop index (0) instead of name (Also both with and without -Passthru)
```
PS C:\Windows\System32> Set-DesktopWallpaper -Desktop 0 -Path 'C:\Users\Joe\Desktop\Test.png' -Verbose
VERBOSE: Set name of desktop number 0 ('General') to 'C:\Users\Joe\Desktop\Test.png'
```

**Comment by MScholtes** [comment]
Hello @ThioJoe,

ok, there are two issues combining, a copy paste error that gives wrong messages and a change in the API with 24H2.

Since I do not have **Win 11 24H2**, I made a "good luck" update of **Virtualdesktop** to Version 1.5.8 today, please try.

Greetings

Markus

**Comment by ThioJoe** [comment]
Yep that seems to have fixed the wallpaper change issue
