### ISSUE TITLE
Find desktop with given name or create if necessary

### ISSUE THREAD

**Issue by ComFreek** [MScholtes/PSVirtualDesktop#6]
For my use case, I needed a function that, for a given name, either finds a pre-existing desktop with that name or creates a new one with that name if none could be found.

I have written such a function below and just wanted to share it with you :smile:
I leave it to you to decide what to do with it.
(Not sure if the functionality is needed often enough to merit addition to your module, so perhaps, just linking this issue code from the readme as an example might be good enough :smile:)

PS: Thank you very much for this module! It's highly useful for automating my daily workflows.

```powershell
function Request-NamedDesktop {
	<#
		.SYNOPSIS
			Retrieves or creates (if non-existing) the virtual desktop with the given name.
		
		.INPUTS
			The desktop name can be piped into this function.

		.OUTPUTS
			A virtual desktop with the given name.

		.EXAMPLE
			Request-NamedDesktop "My Secret Desktop"
		.EXAMPLE
			"My Secret Desktop" | Request-NamedDesktop | Switch-Desktop
		
		.NOTES
			The function assumes that the PSVirtualDesktop module [0] is installed.

			[0]: https://github.com/MScholtes/PSVirtualDesktop
	#>
	param(
		<#
			The name of the virtual desktop to retrieve or create (if non-existing)
		#>
		[Parameter(Mandatory=$true, ValueFromPipeline=$true)]
		[ValidateNotNullOrEmpty()]	
		[string]$name
	)

	$desktop = Get-DesktopList | Where-Object Name -eq $name | Select-Object -First 1

	# The if condition below is susceptible to a TOCTOU bug (https://en.wikipedia.org/wiki/Time-of-check_to_time-of-use).
	# But this is probably okay since virtual desktops aren't something that is created every second.
	if ($desktop) {
		Get-Desktop -Index $desktop.Number
	} else {
		$desktop = New-Desktop
		$desktop | Set-DesktopName -Name $name
		$desktop
	}
}
```

**Comment by MScholtes** [comment]
Hello ComFreek,

what a great idea. But I also think that the function is too special for integration into the module. I will see if I can use it as an example.

Greetings

Markus

**Comment by MScholtes** [comment]
Closed since no response for about 3 weeks

**Comment by ComFreek** [comment]
@MScholtes Oh, I thought you would take some action. But fine for me anyway :smile:

**Comment by MScholtes** [comment]
Hello ComFreek,

added your function to the example file **_Example.ps1_**. Thank you very much.

It took quite a long time, as I hardly have any time on the computer (due to childcare) because of the Corona crisis. I apologise for this.

Greetings

Markus
