### ISSUE TITLE
`Move-Window` run-time error

### ISSUE THREAD

**Issue by ZzZombo** [MScholtes/PSVirtualDesktop#7]
```powershell
> Move-Window -Desktop (Get-CurrentDesktop) -Hwnd 328668 -Verbose # NOTE: the handle provided is valid.
VERBOSE: Moving window to desktop number 0 ('Desktop 1')
MethodInvocationException: C:\Users\Boss\Documents\PowerShell\Modules\VirtualDesktop\1.3.0\VirtualDesktop.ps1:1799
Line |
1799 |          $Desktop.MoveWindow([IntPtr]$Hwnd)
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "MoveWindow" with "1" argument(s): "Marshalling as IInspectable is not supported in
     | the .NET runtime."
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
Given valid values for both parameters, this commandlet always crashes with this error.

**Comment by MScholtes** [comment]
Hello ZzZombo,

PSVirtualDesktop is NOT compatible to Powershell Core 7.1, only to Powershell Core 7.0!

I habe no idea why Microsoft limited support for platform API with Powershell Core 7.1, I also have no idea what to do about it. Maybe it works with Powershell Core 7.2 or .Net 5 again?

I updated the readme page.

Greetings

Markus

**Comment by MScholtes** [comment]
Clolsing the issue since there was no reply for over a month.

**Comment by grietine** [comment]
Is there a way to overcome this limitation or maybe there is something else that I'm missing or changed during a year to solve the same problem?

**Problem:**
This command works as expected on PowerShell 5.1.19041.1320, but doesn't work with PowerShell Core 7.2.1:
`Move-Window -Desktop (Get-Desktop -Index 1) -Hwnd (Get-Process notepad)[0].MainWindowHandle | Out-Null`

**Exception:**
`MethodInvocationException: C:\Users\User\Documents\PowerShell\Modules\VirtualDesktop\1.4.1\VirtualDesktop.ps1:2241 Line | 2241 | $Desktop.MoveWindow($Hwnd) | ~~~~~~~~~~~~~~~~~~~~~~~~~~ | Exception calling "MoveWindow" with "1" argument(s): "Marshalling as IInspectable is not supported in the .NET runtime."`

**OS:**

- Windows 10 Enterprise
- Version: 21H2
- OS build: 19044.1415

**Comment by MScholtes** [comment]
Hello @grietine,

_.Net Core_ and with it _Powershell Core_ are platform independent implementations that work on Linux too. To guarantuee this Microsoft is removing the possibilities to call _APIs_ that are unique to _Windows_.

Since _virtual desktops_ are unique to _Windows_, there is no way to call their _API_ in _Powershell Core_. I can't do anything about ist, please use _Windows Powershell_.

Greetings

Markus
