### ISSUE TITLE
Set-DesktopName no longer functional

### ISSUE THREAD

**Issue by SinnGit** [MScholtes/PSVirtualDesktop#9]
I caught the comment in another open issue that Set-DesktopName was not functioning in Powershell Core.  It seems that Set-DesktopName is no longer functional for older versions of Powershell either.  No errors whatsoever, the cmdlet acts as if it has made a change, but never actually does so.  

 
PS C:\Users\> Set-DesktopName -Name "Excel" -desktop 1
PS C:\Users\> Get-DesktopList      

Number Name      Visible
------ ----      -------
     0 Desktop 1    True
     1 Desktop 2   False
     2 Desktop 3   False
     3 Desktop 4   False
     4 Desktop 5   False
     5 Desktop 6   False

PS C:\Users\> get-host | select version

Version
-------
5.1.18362.1171

PS C:\Users\> get-module virtualdesktop | select version

Version
-------
1.3.0

**Comment by MScholtes** [comment]
Hello SinnGit,

for most of the functions of **PSVirtualDesktop** an underlying function of the Windows API is used, so it is with the function **Set-DesktopName**. But the feature to name desktops was introduced to Windows first with _Windows 10 version 20H1_ (and you are running _Windows 10 version 1903_), if you want to use it, you have to update your Windows.

Greetings

Markus

**Comment by SinnGit** [comment]
Hi Markus,

I'm actually running 1909 on this system

PS C:\Users\> [environment]::OSVersion.Version


Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      18363  0

**Comment by MScholtes** [comment]
Hello SinnGit,

OK, I understand. Microsoft did not update Powershell when they updated Windows 10 1903 (Build 18362) to 1909 (Build 18363). So the Powershell version led me to the wrong version of the Windows you're using.

But this doesn't change the reason and solution for the issue.

Greetings

Markus

**Comment by MScholtes** [comment]
Closed due to no response for several weeks
